name: Metrics
on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
inputs:
  base:
    description: Metrics base content
    default: header

  template:
    description: Template to use
    default: classic
  
  # 📅 Isometric commit calendar
  
  # Enable or disable plugin
  plugin_isocalendar:
    description: Display an isometric view of your commits calendar
    default: yes
  
  # Set time window shown by isometric calendar
  plugin_isocalendar_duration:
    description: Set time window shown by isometric calendar
    default: half-year

  # ====================================================================================
  # 🏆 Achievements
  
  # Enable or disable plugin
  plugin_achievements:
    description: Display achievements
    default: yes
  
  # Minimal rank to display
  plugin_achievements_threshold:
    description: Display rank minimal threshold
    default: B
  
  # Display secrets achievements unlocked
  plugin_achievements_secrets:
    description: Display unlocked secrets achievements
    default: yes
  
  # Achievements display style
  plugin_achievements_display:
    description: Achievements display style
    default: detailed
  
  # Number of achievements events to display
  # Set to 0 to disable limitations
  plugin_achievements_limit:
    description: Maximum number of achievements to display
    default: 3
  
  # List of unlocked achievements to hide
  # Names must be given in lower case, without rank adjective
  plugin_achievements_ignored:
    description: Unlocked achievements to hide
    default: ""
  
  # List of unlocked achievements to display
  # Names must be given in lower case, without rank adjective
  # Using this option is equivalent of using "plugin_achievements_ignored" with all existing achievements but the ones listed
  plugin_achievements_only:
    description: Unlocked achievements to display
    default: ""
  
  # ====================================================================================
  # 🎩 Notable contributions
  
  # Enable or disable plugin
  plugin_notable:
    description: Display notable contributions in organizations
    default: yes
  
  # Supported fields are "stars", "forks" and "watchers"
  plugin_notable_filter:
    description: Query filter
    default: ""
  
  # Filter repositories depending on which type of account it is hosted
  plugin_notable_from:
    description: Filter by repository host account type
    default: organization

  # Also display repository name along with organization name
  plugin_notable_repositories:
    description: Also display repository name
    default: no
  
