name: Metrics
on:
  schedule:
    - cron: "0 16 * * *"
  push:
    branches:
      - master
      - main
  workflow_dispatch:
jobs:
  github-metrics-personal:
    runs-on: ubuntu-latest
    steps:

      - name: 🦑 Personal metrics
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header
          plugin_gists: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_notable: yes
          plugin_notable_from: organization
          plugin_notable_types: commit
          config_timezone: America/Sao_Paulo
          output_action: pull-request-squash
